version: '3.8'

services:
  # Your CDK Mint service
  cdk-mintd:
    build: .
    ports:
      - "3338:3338"
    environment:
      # OpenTelemetry configuration
      - OTEL_SERVICE_NAME=cdk-mintd
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_SERVICE_NAMESPACE=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TIMEOUT=10000
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=docker,service.instance.id=mintd-01
      - RUST_LOG=info
    depends_on:
      - otel-collector
      - jaeger
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--enable-feature=otlp-write-receiver'

    networks:
      - observability

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3011:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability

networks:
  observability:
    driver: bridge