version: '3.8'

services:
  # Your CDK Mint service
  cdk-mintd:
    build: .
    ports:
      - "3338:3338"
    environment:
      # OpenTelemetry configuration
      - RUST_LOG=info
    depends_on:
      - prometheus
      - grafana
    networks:
      - cdk

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--enable-feature=otlp-write-receiver'

    networks:
      - cdk

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3011:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - cdk

networks:
  cdk:
    driver: bridge