[package]
name = "cdk-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]
name = "cdk_ffi"

[features]
default = ["auth"]
auth = ["cdk/auth"]

[dependencies]
cdk = { workspace = true, features = ["wallet"] }
cdk-common = { workspace = true }

# UniFFI dependencies
uniffi = { version = "0.29", features = ["cli"] }

# Core dependencies
rand = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
bip39 = { workspace = true }

# Database storage for wallet
cdk-sqlite = { workspace = true }


[dev-dependencies]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
