[package]
name = "cdk-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]
name = "cdk_ffi"

[features]
default = ["auth"]
auth = ["cdk/auth"]

[dependencies]
bip39 = { workspace = true }
cdk = { workspace = true, features = ["wallet"] }
cdk-common = { workspace = true }
cdk-sqlite = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
uniffi = { version = "0.29", features = ["cli"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }


[dev-dependencies]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
