name: Nutshell integration

on: [push, pull_request]

jobs:
  nutshell-integration-tests:
    name: Nutshell Mint Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build-ci-image
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Test Nutshell
        run: docker run --rm -v $(pwd):/usr/src/app ${{ needs.build-ci-image.outputs.image_tag }} just test-nutshell
      - name: Show logs if tests fail
        if: failure()
        run: docker logs nutshell

  nutshell-wallet-integration-tests:
    name: Nutshell Wallet Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build-ci-image
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Pull Nutshell Docker image
        run: docker pull cashubtc/nutshell:latest
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Test Nutshell Wallet
        run: |
          docker run --rm -v $(pwd):/usr/src/app ${{ needs.build-ci-image.outputs.image_tag }} just nutshell-wallet-itest
      - name: Show Docker logs if tests fail
        if: failure()
        run: docker logs nutshell-wallet || true
